added SudokuMove and SudokuPuzzle class skeletons
JACorley1/UWG-SE2-Spring22-Team1 pull request #14
Opened 2022-02-17 01:30 UTC by MatthewThompson35

2022-02-17 01:56 UTC, bfreder1 requested changes
Neither class has a package declaration and should be grouped together in a sudoku package in the model package. Outside of that, they function fine as skeletons.

2022-02-17 04:23 UTC, TakenouchiTR requested changes

2022-02-17 04:23 UTC, TakenouchiTR commented on code/model/sudoku/SudokuPuzzle.java
> + */
Missing author and version

2022-02-17 04:23 UTC, TakenouchiTR commented on code/model/sudoku/SudokuMove.java
> + */
Missing author and version

2022-02-17 04:23 UTC, TakenouchiTR commented on code/model/sudoku/SudokuPuzzle.java
> +        this.selectedNumber = null;
Unless I'm missing something, you shouldn't be able to set an `int` to `null` in Java.
Recommend using a default value, such as 0 or -1.

2022-02-17 04:23 UTC, TakenouchiTR commented on code/model/sudoku/SudokuPuzzle.java
> +        return null;
Method should return that answer for a specified `column` and `row`, not return null.

2022-02-17 04:23 UTC, TakenouchiTR commented on code/model/sudoku/SudokuPuzzle.java
> +        return false;
Should return whether a number is locked at a specified `row` and `column`; 

`return this.numberLocks[row][column];`.

2022-02-17 04:23 UTC, TakenouchiTR commented on code/model/sudoku/SudokuPuzzle.java
> +    }
I intended for these to be getting the number at a given position, which is why the class diagram specifies a `row` and `column` in the method header.

Recommend changing the name of the current method to be plural (`getNumbers()`), and making a second method that follows what is in the class diagram.

2022-02-20 21:19 UTC, TakenouchiTR requested changes
Please make sure not to add .~ files.

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @postcondition this.numbers = new int[9][9] && this.numberLocks = new boolean[9][9] && this.defaultAnswer = new int[9][9] && this.selectedNumber = -1 && this.moveHistory = new Stack<SudokuMove
`=` should be `==`
ie: `this.numberLocks = new boolean[9][9]` => `this.numberLocks == new boolean[9][9]`

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @return this.numbers
We can't see what a private field is from the outside. The return should not mention it, and should tell the developer what the return value is in words.

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @return this.moveHistory
We can't see what a private field is from the outside. The return should not mention it, and should tell the developer what the return value is in words.

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @return this.numberLocks
We can't see what a private field is from the outside. The return should not mention it, and should tell the developer what the return value is in words.

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @postcondition this.numberLocks[row][column] = lock
See above about `=` and `==`

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @postcondition this.selectedNumber = number
See above `=`

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +    /***
pls fix ***

2022-02-20 21:19 UTC, TakenouchiTR commented on code/src/test/java/habit_mode/test/model/sudoku/sudokuPuzzle/TestConstructor.java
> +		);
Inconsistent tabbing

2022-02-20 21:23 UTC, bfreder1 commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @return this.numberLocks
Needs new line

2022-02-20 21:24 UTC, bfreder1 commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @param column the column
Re-order this doc

2022-02-20 21:24 UTC, bfreder1 commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @return this.moveHistory
Needs new line

2022-02-20 21:24 UTC, bfreder1 commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @return this.numbers
Needs some new lines

2022-02-20 21:25 UTC, bfreder1 commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @postcondition this.numbers = new int[9][9] && this.numberLocks = new boolean[9][9] && this.defaultAnswer = new int[9][9] && this.selectedNumber = -1 && this.moveHistory = new Stack<SudokuMove
Needs new line

2022-02-22 14:47 UTC, Steven-Carriger commented on code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
> +     * @param lock
same as before

2022-02-22 14:48 UTC, Steven-Carriger requested changes
Overall, everything looks fine. Just a couple documentation issues that I have noticed.

2022-02-24 16:02 UTC, Steven-Carriger approved these changes
All changes have been implemented.

2022-02-24 16:02 UTC, merged