Update usecases
JACorley1/UWG-SE2-Spring22-Team1 pull request #38
Opened 2022-03-09 17:28 UTC by Steven-Carriger

Updated the use case scenarios and added additional ones to be up to date with our ideas for the features in this sprint.

2022-03-09 20:23 UTC, TakenouchiTR requested changes
Overall very good. I only have one hard change and one possible change, depending on what we decide to do with registration.

2022-03-09 20:23 UTC, TakenouchiTR commented on documentation/Use Case Scenarios/Completing Habit Scenario.txt
> +4.	The user selects "yes" confirming they want the habit marked as complete
The user should be able to check multiple habits at once, then mark them all as complete with a single prompt.

2022-03-09 20:23 UTC, TakenouchiTR commented on documentation/Use Case Scenarios/Registering Account Scenario.txt
> +4.	The user is taken to a registration page
We may or may not have to update this after our discussion, depending on what @bfreder1 wants to do.

2022-03-17 00:32 UTC, TakenouchiTR requested changes

2022-03-17 00:32 UTC, TakenouchiTR commented on documentation/Use Case Scenarios/Completing Habit Scenario.txt
> +5.	The habits are marked as complete
Check boxes should not bring up a confirmation box every time. Users should be able to checks multiple habits, then press a button to complete them. Once the button is pressed, it should ask if the user is sure.

2022-04-03 19:15 UTC, TakenouchiTR requested changes
All tabbing was removed entirely, when it should have just been fixed to be consistent.
There should also probably be a blank line between the primary and alternative flows, just to make the text easier to read.

2022-04-06 20:02 UTC, MatthewThompson35 approved these changes
Tabbing is now consistent.

2022-04-06 20:03 UTC, merged